print('now i need money') 
input('give me some money  : ')
money = input('Give me some money : ')
print('here is your money',money)
first_money=input('kodom ali,dosto kichu taka dey: ')
sceond_money=input('payara begum,dosto kichu taka dey: ')
first_money_int=int(first_money)
sceond_money_int=int(sceond_money)
print(f"money i got' {first_money} and {sceond_money}")
total= (first_money_int+sceond_money_int)
print('total money i got: ',total)